version = 0.1

[default.deploy.parameters]
stack_name = "TechChallenge4-Processor"
resolve_s3 = true
s3_prefix = "TechChallenge4-Processor"
capabilities = "CAPABILITY_IAM"

parameter_overrides = "DynamoDbTableName=\"Feedbacks\" AdminEmail=\"gustavo.jog+admin@hotmail.com\" SourceEmail=\"gustavo.jog+no-reply@hotmail.com\" IdempotencyTableName=\"PdfJobs\" ReportsBucketName=\"feedback-reports-bucket\" PdfUrlDays=20 ReportSchedule=\"rate(1 day)\""

[default.global.parameters]
region = "sa-east-1"